---
title: "Run gt_admixture for vignette"
output: html_document
date: "2025-03-03"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
vcf_path <-
  system.file("/extdata/anolis/punctatus_t70_s10_n46_filtered.recode.vcf.gz",
    package = "tidypopgen"
  )
anole_gt <-
  gen_tibble(vcf_path, quiet = TRUE, backingfile = tempfile("anolis_"))
pops_path <- system.file("/extdata/anolis/plot_order_punctatus_n46.csv",
  package = "tidypopgen"
)
pops <- readr::read_csv(pops_path, show_col_types = FALSE)
anole_gt <- anole_gt %>% mutate(id = gsub("punc_", "", .data$id, ))
anole_gt <- anole_gt %>% mutate(population = pops$pop[match(pops$ID, .data$id)])
```


```{r}
anole_gt <- anole_gt %>% group_by(population)

anole_adm <- gt_admixture(
  x = anole_gt,
  k = 2:6,
  n_runs = 1,
  crossval = TRUE,
  seed = 1
)
```

```{r}
runs <- c(1)
k_values <- c(2:6)
q_matrices <- list()
p_matrices <- list()
logs <- list()
dir <- system.file("/extdata/a03_admixture", package = "tidypopgen")

for (x in k_values) {
  q_matrices[[x]] <- list()

  for (i in runs) {
    q_matrices[[x]][[i]] <- get_q_matrix(anole_adm, k = x, run = i)

    gz_file <- gzfile(paste0(dir, "/K", x, "run", i, ".Q.gz"), "wt")
    write.table(q_matrices[[x]][[i]],
      file = gz_file,
      col.names = FALSE, row.names = FALSE, quote = FALSE
    )
    close(gz_file)
  }
}

for (x in k_values) {
  p_matrices[[x]] <- list()

  for (i in runs) {
    p_matrices[[x]][[i]] <- get_p_matrix(anole_adm, k = x, run = i)

    gz_file <- gzfile(paste0(dir, "/K", x, "run", i, ".P.gz"), "wt")
    write.table(p_matrices[[x]][[i]],
      file = file,
      col.names = FALSE, row.names = FALSE, quote = FALSE
    )
    close(gz_file)
  }
}

k_values <- 1:5

for (x in k_values) {
  logs[[x]] <- list()

  logs[[x]] <- anole_adm$log[[x]]

  file <- gzfile(paste0(dir, "/K", x, "run", i, ".log.gz"), "wt")
  write.table(logs[[x]],
    file = file,
    col.names = FALSE, row.names = FALSE, quote = FALSE
  )
  close(file)
}
```
