#' Run ADMIXTURE from R
#'
#' This function runs ADMIXTURE, taking either a `gen_tibble` or a file as an input.
#'
#' @details This is a wrapper for the command line program ADMIXTURE. It can either
#' use a binary present in the main environment, or use a copy installed in a conda
#' environment. If the package `tidygenclust` is installed, and its conda environment
#' has been set up with `ADMIXTURE` in it (the default), it will automatically
#' use that version unless you change `conda_env` to "none".
#' @param x a `gen_tibble` or a character giving the path of the input PLINK bed file
#' @param k an integer giving the number of clusters
#' @param crossval boolean, should cross validation be used to assess the fit (defaults ot FALSE)
#' @param n_cores number of cores (defaults to 1)
#' @param seed the seed for the random number generator (defaults to NULL)
#' @param out the output path for the results. It defaults to NULL, in which case, if `x` is a `gen_tibble`, the output
#' will be written to a temporary directory; esle if `x` is the path of a PLINK bed file,
#' the output will be saved in the same directory as the input file.
#' @param conda_env the name of the conda environment to use. If set to "auto", the default,
#' a copy from `tidygenclust` will be preferred if available, otherwise a local copy will
#' be used. "none" forces the use of a local copy, whilst any other string will
#' direct the function to use a custom conda environment.
#' @return an object of class `gt_admix` consing of a list with the following elements:
#' - `k` the number of clusters
#' - `Q` a matrix with the admixture proportions
#' - `P` a matrix with the allele frequencies
#' - `log` a log of the output generated by ADMIXTURE (usually printed on the screen when running from the command line)
#' - `cv` the cross validation error (if `crossval` is TRUE)
#' @export


gt_admixture <- function (x, k, crossval = FALSE, n_cores = 1, seed = NULL,
                          out = NULL, conda_env="auto"){
  # if x is a character, check that it is file that exists
  if (is.character(x)) {
    if (!file.exists(x)) {
      stop("The file ", x, " does not exist")
    }
    input_file <- x
  } else { # if x is a gen_tibble
    if (!methods::is(x, "gen_tibble")) {
      stop("x must be a gen_tibble or a character")
    }
    # write the gen_tibble to a temp file
    input_file <- gt_as_plink(x, file = tempfile(fileext = "."))
  }

  if (is.null(out)){
    out <-dirname(input_file)
  }

  # cast k as an integer
  k <- as.integer(k)

  # set the arguments for admixture
  admixture_args <- paste(input_file, k)
  if (crossval) {
    admixture_args <- paste(admixture_args, "--cv")
  }
  if (n_cores > 1) {
    admixture_args <- paste(admixture_args, paste0("-j", n_cores))
  }
  if (!is.null(seed)) {
    admixture_args <- paste(admixture_args, paste0("-s ", seed))
  }
  # set and check the conda environemnt
  # if there is no reticulate
  if (!requireNamespace("reticulate", quietly = TRUE)) {
    # but we have not set conda_env to none
    if (conda_env!="none"){
      # if we have auto, set to none
      if (conda_env == "auto"){
        conda_env <- "none"
      } else {
        stop("The package reticulate is needed to use a conda environemnt in R.")
      }
    }
  } else { # if reticulate is available
    # if we have "auto" and the conda environment rtidygenclust does not exist, or
    if (conda_env =="auto") {
      if (("rfastmixture" %in% reticulate::conda_list()[["name"]])){
        conda_env <- "rfastmixture"
      } else {
        conda_env <- "none"
      }
      # check that the conda environment does exist
      if ((conda_env !="none") && (!conda_env %in% reticulate::conda_list()[["name"]])){
        stop("The conda environment ", conda_env, " does not exist.")
      }
    }
  }
  # if we conda_env is none
  if (conda_env == "none") {
    # use the system version of admixture (if it is installed)
    if (system2("which", args = "admixture", stdout = NULL) == 0) {
      # store working directory
      wd <- getwd()
      # change to the directory of the input file
      setwd(dirname(input_file))
      adm_out <- system2("admixture", args = admixture_args, stdout = TRUE)
      # change back to the original working directory
      setwd(wd)
    } else {
      stop("admixture is not installed in this path")
    }
  } else {
    reticulate::conda_run2("admixture", args = admixture_args,
                           conda = conda_env)
  }

  # read the output
  #browser()
  output_prefix <- file.path(out, gsub(".bed", "", basename(input_file)))
  Q <- utils::read.table(paste(output_prefix,k,"Q",sep="."), header = FALSE)
  P <- utils::read.table(paste(output_prefix,k,"P",sep="."), header = FALSE)
  res <- list(k = k, Q = list(q_matrix(Q)), P = list(P), log = list(adm_out))
  class(res) <- c("gt_admix","list")
  if (crossval) {
    cv <- utils::read.table(paste0(input_file, ".cv"), header = FALSE)
    res$csv <- list(cv)
  }
  return(res)

}


