# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

alt_freq_dip_pseudo_cpp <- function(BM, rowInd, colInd, ploidy, ncores, as_counts) {
    .Call(`_tidypopgen_alt_freq_dip_pseudo_cpp`, BM, rowInd, colInd, ploidy, ncores, as_counts)
}

compute_np_mn <- function(n) {
    .Call(`_tidypopgen_compute_np_mn`, n)
}

fbm256_prod_and_rowSumsSq <- function(BM, ind_row, ind_col, center, scale, V) {
    .Call(`_tidypopgen_fbm256_prod_and_rowSumsSq`, BM, ind_row, ind_col, center, scale, V)
}

grouped_alt_freq_dip_pseudo_cpp <- function(BM, rowInd, colInd, groupIds, ngroups, ploidy, ncores, as_counts) {
    .Call(`_tidypopgen_grouped_alt_freq_dip_pseudo_cpp`, BM, rowInd, colInd, groupIds, ngroups, ploidy, ncores, as_counts)
}

grouped_missingness_cpp <- function(BM, rowInd, colInd, groupIds, ngroups, ncores) {
    .Call(`_tidypopgen_grouped_missingness_cpp`, BM, rowInd, colInd, groupIds, ngroups, ncores)
}

grouped_summaries_dip_pseudo_cpp <- function(BM, rowInd, colInd, groupIds, ngroups, ploidy, ncores) {
    .Call(`_tidypopgen_grouped_summaries_dip_pseudo_cpp`, BM, rowInd, colInd, groupIds, ngroups, ploidy, ncores)
}

gt_grouped_pi_diploid <- function(BM, rowInd, colInd, groupIds, ngroups, ncores) {
    .Call(`_tidypopgen_gt_grouped_pi_diploid`, BM, rowInd, colInd, groupIds, ngroups, ncores)
}

gt_ind_hetero <- function(BM, rowInd, colInd, ncores) {
    .Call(`_tidypopgen_gt_ind_hetero`, BM, rowInd, colInd, ncores)
}

gt_pi_diploid <- function(BM, rowInd, colInd, ncores) {
    .Call(`_tidypopgen_gt_pi_diploid`, BM, rowInd, colInd, ncores)
}

SNPHWE2_R <- function(obs_hets, obs_hom1, obs_hom2, midp) {
    .Call(`_tidypopgen_SNPHWE2_R`, obs_hets, obs_hom1, obs_hom2, midp)
}

hwe_on_matrix <- function(geno_counts, midp) {
    .Call(`_tidypopgen_hwe_on_matrix`, geno_counts, midp)
}

gt_grouped_hwe <- function(BM, rowInd, colInd, groupIds, ngroups, midp) {
    .Call(`_tidypopgen_gt_grouped_hwe`, BM, rowInd, colInd, groupIds, ngroups, midp)
}

pairwise_fst_hudson_loop <- function(pairwise_combn, n, freq_alt, freq_ref, by_locus, return_num_dem) {
    .Call(`_tidypopgen_pairwise_fst_hudson_loop`, pairwise_combn, n, freq_alt, freq_ref, by_locus, return_num_dem)
}

pairwise_fst_nei87_loop <- function(pairwise_combn, n, het_obs, freq_alt, freq_ref, by_locus, return_num_dem) {
    .Call(`_tidypopgen_pairwise_fst_nei87_loop`, pairwise_combn, n, het_obs, freq_alt, freq_ref, by_locus, return_num_dem)
}

pairwise_fst_wc84_loop <- function(pairwise_combn, n, freq_alt, het_obs, by_locus, return_num_dem) {
    .Call(`_tidypopgen_pairwise_fst_wc84_loop`, pairwise_combn, n, freq_alt, het_obs, by_locus, return_num_dem)
}

read_packedancestry <- function(filename, BM, tab) {
    .Call(`_tidypopgen_read_packedancestry`, filename, BM, tab)
}

increment_as_counts <- function(k, k2, na_mat, dos_mat, BM, rowInd, colInd) {
    invisible(.Call(`_tidypopgen_increment_as_counts`, k, k2, na_mat, dos_mat, BM, rowInd, colInd))
}

increment_ibs_counts <- function(k, k2, genotype0, genotype1, genotype2, BM, rowInd, colInd) {
    invisible(.Call(`_tidypopgen_increment_ibs_counts`, k, k2, genotype0, genotype1, genotype2, BM, rowInd, colInd))
}

increment_king_numerator <- function(k, n_Aa_i, genotype0, genotype1, genotype2, genotype_valid, BM, rowInd, colInd) {
    invisible(.Call(`_tidypopgen_increment_king_numerator`, k, n_Aa_i, genotype0, genotype1, genotype2, genotype_valid, BM, rowInd, colInd))
}

vcf_loci_table <- function(filename) {
    .Call(`_tidypopgen_vcf_loci_table`, filename)
}

vcf_genotypes_to_fbm <- function(filename, BM, biallelic, missing_value, n_header_lines) {
    .Call(`_tidypopgen_vcf_genotypes_to_fbm`, filename, BM, biallelic, missing_value, n_header_lines)
}

write_to_FBM <- function(BM, allele_counts, col_start, n_loci, ncores) {
    invisible(.Call(`_tidypopgen_write_to_FBM`, BM, allele_counts, col_start, n_loci, ncores))
}

