# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

SNPHWE2 <- function(obs_hets, obs_hom1, obs_hom2, midp) {
    .Call(`_tidypopgen_SNPHWE2`, obs_hets, obs_hom1, obs_hom2, midp)
}

SNPHWE_t <- function(obs_hets, obs_hom1, obs_hom2, thresh) {
    .Call(`_tidypopgen_SNPHWE_t`, obs_hets, obs_hom1, obs_hom2, thresh)
}

SNPHWE_midp_t <- function(obs_hets, obs_hom1, obs_hom2, thresh) {
    .Call(`_tidypopgen_SNPHWE_midp_t`, obs_hets, obs_hom1, obs_hom2, thresh)
}

increment_ibs_counts <- function(K, K2, part_temp0, part_temp1, part_temp2, BM, rowInd, colInd) {
    invisible(.Call(`_tidypopgen_increment_ibs_counts`, K, K2, part_temp0, part_temp1, part_temp2, BM, rowInd, colInd))
}

increment_king_numerator <- function(K, part_temp0, part_temp1, part_temp2, BM, rowInd, colInd) {
    invisible(.Call(`_tidypopgen_increment_king_numerator`, K, part_temp0, part_temp1, part_temp2, BM, rowInd, colInd))
}

