# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

SNPHWE2 <- function(obs_hets, obs_hom1, obs_hom2, midp) {
    .Call(`_tidypopgen_SNPHWE2`, obs_hets, obs_hom1, obs_hom2, midp)
}

SNPHWE_t <- function(obs_hets, obs_hom1, obs_hom2, thresh) {
    .Call(`_tidypopgen_SNPHWE_t`, obs_hets, obs_hom1, obs_hom2, thresh)
}

SNPHWE_midp_t <- function(obs_hets, obs_hom1, obs_hom2, thresh) {
    .Call(`_tidypopgen_SNPHWE_midp_t`, obs_hets, obs_hom1, obs_hom2, thresh)
}

increment_as_counts <- function(k, k2, na_mat, dos_mat, BM, rowInd, colInd) {
    invisible(.Call(`_tidypopgen_increment_as_counts`, k, k2, na_mat, dos_mat, BM, rowInd, colInd))
}

increment_ibs_counts <- function(k, k2, genotype0, genotype1, genotype2, BM, rowInd, colInd) {
    invisible(.Call(`_tidypopgen_increment_ibs_counts`, k, k2, genotype0, genotype1, genotype2, BM, rowInd, colInd))
}

increment_king_numerator <- function(k, n_Aa_i, genotype0, genotype1, genotype2, genotype_valid, BM, rowInd, colInd) {
    invisible(.Call(`_tidypopgen_increment_king_numerator`, k, n_Aa_i, genotype0, genotype1, genotype2, genotype_valid, BM, rowInd, colInd))
}

