#' Print a summary of a merge report
#'
#' This function creates a summary of the merge report generated by
#' [rbind_dry_run()]
#'
#' @param report a list generated by [rbind_dry_run()]
#' @param ref_label the label for the reference dataset (defaults to "reference")
#' @param target_label the label for the target dataset (defaults to "target")
#' @returns NULL (prints a summary to the console)
#' @rdname rbind_dry_run_summary
#' @export

summary.rbind_report <- function(report,
                                    ref_label="reference",
                                    target_label="target"){
  cat("dataset:", ref_label,"\n")
  cat("number of SNPs:", nrow(report$ref), "reduced to",sum(!is.na(report$ref$new_id)),"\n")
  cat("(",sum(report$ref$ambiguous),"are ambiguous, of which",
      (sum(report$ref$ambiguous & is.na(report$ref$new_id)))," were removed)\n")
  cat("-----------------------------\n")
  cat("dataset:", target_label,"\n")
  cat("number of SNPs:", nrow(report$target), "reduced to",sum(!is.na(report$target$new_id)),"\n")
  cat("(",sum(report$target$to_flip),"were flipped to match the reference set)\n")
  cat("(",sum(report$target$ambiguous),"are ambiguous, of which",
      (sum(report$target$ambiguous & is.na(report$target$new_id))),"were removed)")
}
