# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

name: test-coverage

permissions: read-all

jobs:
  test-coverage:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: |
            any::covr
            any::xml2
            admixtools=?ignore
          needs: coverage

      - name: install admixtools
        run: |
          install.packages("admixtools", repos = c("https://evolecolgroup.r-universe.dev", "https://cloud.r-project.org"))
        shell: Rscript {0}



      - name: Get ADMIXTURE for linux
        run: |
             mkdir admixture
             cd admixture
             wget https://dalexander.github.io/admixture/binaries/admixture_linux-1.3.0.tar.gz
             tar -xvzf admixture_linux-1.3.0.tar.gz
             cd ..
             echo "$PWD/admixture/dist/admixture_linux-1.3.0" >> "$GITHUB_PATH"


      - name: Test coverage
        run: |
          cov <- covr::package_coverage(
            type = "all",
            quiet = FALSE,
            clean = FALSE,
            install_path = file.path(normalizePath(Sys.getenv("RUNNER_TEMP"), winslash = "/"), "package")
          )
          covr::to_cobertura(cov)
        shell: Rscript {0}

      - uses: codecov/codecov-action@v4
        with:
          fail_ci_if_error: ${{ github.event_name != 'pull_request' && true || false }}
          file: ./cobertura.xml
          plugin: noop
          disable_search: true
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Show testthat output
        if: always()
        run: |
          ## --------------------------------------------------------------------
          find '${{ runner.temp }}/package' -name 'testthat.Rout*' -exec cat '{}' \; || true
        shell: bash

      - name: Upload test results
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-test-failures
          path: ${{ runner.temp }}/package
